### ISSUE TITLE
Sometimes failing with Broken Pipe in Github Actions

### ISSUE THREAD

**Issue by wozeparrot** [vegardit/fast-apt-mirror.sh#1]
Noticed here: https://github.com/tinygrad/tinygrad/actions/runs/5790180583/job/15692747572

Relevant log section:

```
APT::Acquire::Retries "3";
+ curl -sSfL --retry 3 --max-time 6 https://raw.githubusercontent.com/vegardit/fast-apt-mirror.sh/v1/fast-apt-mirror.sh -o /home/runner/fast-apt-mirror.sh
Current mirror: http://azure.archive.ubuntu.com/ubuntu/ (/etc/apt/sources.list)
Randomly selecting 20 mirrors...done
Checking health status of 20 mirrors....................done
 -> 15 mirrors are reachable and up-to-date
http://azure.archive.ubuntu.com/ubuntu/
https://mirrors.xtom.com/ubuntu/
https://mirrors.wikimedia.org/ubuntu/
http://www.club.cc.cmu.edu/pub/ubuntu/
http://ubuntu.phoenixnap.com/ubuntu/
http://ubuntu.mirror.frontiernet.net/ubuntu/
http://repos.forethought.net/ubuntu/
http://plug-mirror.rcac.purdue.edu/ubuntu/
http://mirrors.tripadvisor.com/ubuntu/
http://mirrors.syringanetworks.net/ubuntu-archive/
Speed testing 10 of the available 15 mirrors (sample download size: 1024KB)..........done
/home/runner/fast-apt-mirror.sh: line 337: echo: write error: Broken pipe
21:42:48 Error - exited with status 1 in /home/runner/fast-apt-mirror.sh at line 337:
21:42:48 Error - exited with status 1 in /home/runner/fast-apt-mirror.sh at line 337:
   334	    return $RC_MISC_ERROR
   335	  fi
   336	  fastest_mirror=$(echo "$mirrors_with_speed" | head -1 | cut -d" " -f2)
   337	  fastest_mirror_speed=$(echo "$mirrors_with_speed" | head -1 | cut -d" " -f1 | numfmt --to=iec --suffix=B/s)
   338	  >&2 echo " -> $fastest_mirror ($fastest_mirror_speed) determined as fastest mirror within $(( $(date +%s) - start_at )) seconds"
   339	  if [[ ${verbosity:-} -gt 0 ]]; then
   340	    echo "$mirrors_with_speed" | tail -n +2 | while IFS= read -r mirror; do
```

**Comment by sebthom** [comment]
This is odd. Do you have other cases where it failed? If so did it always fail on the same line?

I cannot really see how `echo "$mirrors_with_speed" | head -1 | cut -d" " -f1 | numfmt --to=iec --suffix=B/s` can fail with a broken pipe. This would mean that one of the commands `head`, `cut` or `numfmt` crashed unexpectedly for some reason.

Even if I feed the variable `mirrors_with_speed` with some invalid entries it does not result in a broken pipe but numfmt complaining about a non numeric value.

**Comment by wozeparrot** [comment]
Yea, I've see this fail on the same line in other runs, can't find them now because I just rerun it which then shows up in the UI as the run having succeeded so I can't tell now which runs have failed previously.

Could actions be randomly cutting something here?

I wanted to use this cuz the azure mirror has been acting inconsistently for the past week.

**Comment by sebthom** [comment]
>Could actions be randomly cutting something here?

Good question. I haven't seen that broken pipe issue before. Everything is possible. 

>I wanted to use this cuz the azure mirror has been acting inconsistently for the past week.

That's the reason why I build this action.

**Comment by roelofvandijk** [comment]
Here's another one:
https://github.com/tinygrad/tinygrad/actions/runs/5794018532/job/15702809194

```

Run vegardit/fast-apt-mirror.sh@v1
Run echo "::group::Linux: Configure fast APT mirror"
Linux: Configure fast APT mirror
  APT::Acquire::Retries "3";
  + curl -sSfL --retry 3 --max-time 6 https://raw.githubusercontent.com/vegardit/fast-apt-mirror.sh/v1/fast-apt-mirror.sh -o /home/runner/fast-apt-mirror.sh
  Current mirror: http://azure.archive.ubuntu.com/ubuntu/ (/etc/apt/sources.list)
  Randomly selecting 20 mirrors...done
  Checking health status of 20 mirrors....................done
   -> 17 mirrors are reachable and up-to-date
  http://azure.archive.ubuntu.com/ubuntu/
  https://mirrors.wikimedia.org/ubuntu/
  https://mirror.servaxnet.com/ubuntu/
  https://mirror.fcix.net/ubuntu/
  https://la.mirrors.clouvider.net/ubuntu/
  http://ubuntu.securedservers.com/
  http://ubuntu.mirrors.pair.com/archive/
  http://ubuntu.mirror.frontiernet.net/ubuntu/
  http://mirrors.rit.edu/ubuntu/
  http://mirrors.maine.edu/ubuntu/
  Speed testing 10 of the available 17 mirrors (sample download size: 1024KB)..........done
  /home/runner/fast-apt-mirror.sh: line 337: echo: write error: Broken pipe
  07:26:57 Error - exited with status 1 in /home/runner/fast-apt-mirror.sh at line 337:
  07:26:57 Error - exited with status 1 in /home/runner/fast-apt-mirror.sh at line 337:
     334	    return $RC_MISC_ERROR
     335	  fi
     336	  fastest_mirror=$(echo "$mirrors_with_speed" | head -1 | cut -d" " -f2)
     337	  fastest_mirror_speed=$(echo "$mirrors_with_speed" | head -1 | cut -d" " -f1 | numfmt --to=iec --suffix=B/s)
     338	  >&2 echo " -> $fastest_mirror ($fastest_mirror_speed) determined as fastest mirror within $(( $(date +%s) - start_at )) seconds"
     339	  if [[ ${verbosity:-} -gt 0 ]]; then
     340	    echo "$mirrors_with_speed" | tail -n +2 | while IFS= read -r mirror; do
  Error: Process completed with exit code 1.
```

**Comment by roelofvandijk** [comment]
Here's a similar issue with a broken pipe on `head` and a potential fix:
https://superuser.com/questions/554855/how-can-i-fix-a-broken-pipe-error

**Comment by sebthom** [comment]
Interesting post, thanks for digging it out! However I doubt that this is the same issue. `head` consumes output from an `echo` which is a bash built-in and the data is available immediately.

Out of interest I tried to provoke the error like this `echo "$variable_with_a_lot_of_lines" | head -1` and could not produce a broken pipe.

**Comment by sebthom** [comment]
I now replaced the usage of `head -1` with a bash built-in construct. Let's see if this prevents the broken pipe issue appearing in your builds.

**Comment by sebthom** [comment]
I checked the logs of the builds in your repo and I don't see any more errors regarding the fast-apt-mirror action. I am going to close the issue for now. Feel free to reopen if the issue reappears.
