### ISSUE TITLE
Doesn't update multiple repos in the same deb822 file (Ubuntu 24.04)

### ISSUE THREAD

**Issue by antonc42** [vegardit/fast-apt-mirror.sh#5]
The `fast-apt-mirror.sh find --apply` feature doesn't update the repo URI if there are multiple repositories in the same deb822-formated file, as is the case by default in Ubuntu 24.04. It appears to only update the first one.

Default Ubuntu 22.04 `/etc/apt/sources.list.d/ubuntu.sources` file (relevant lines):
<pre><code>
Types: deb
URIs: <strong>http://archive.ubuntu.com/ubuntu</strong>
Suites: noble noble-updates noble-backports
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: <strong>http://security.ubuntu.com/ubuntu</strong>
Suites: noble-security
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
</code></pre>

Ubuntu 22.04 `/etc/apt/sources.list.d/ubuntu.sources` file after running `fast-apt-mirror.sh find --apply` (relevant lines):
<pre><code>
Types: deb
URIs: <strong>http://fast.mirror.example.com/ubuntu</strong>
Suites: noble noble-updates noble-backports
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: <strong>http://security.ubuntu.com/ubuntu</strong>
Suites: noble-security
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
</code></pre>

Note that only the URI of the first repository is changed even though both are "main" repos.

The desired behavior would be that both URIs are changed. 

<pre><code>
Types: deb
URIs: <strong>http://fast.mirror.example.com/ubuntu</strong>
Suites: noble noble-updates noble-backports
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: <strong>http://fast.mirror.example.com/ubuntu</strong>
Suites: noble-security
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
</code></pre>

**Comment by sebthom** [comment]
I doubt it would be advisable to point to the security repo to a mirror of the main repo.

**Comment by antonc42** [comment]
I guess that is the recommendation: https://wiki.ubuntu.com/SecurityTeam/FAQ#What_repositories_and_pockets_should_I_use_to_make_sure_my_systems_are_up_to_date.3F

Would it be possible for this to be a non-default override option? Then users who choose could change the security repo to a mirror.

**Comment by sebthom** [comment]
Hm, I think this gets complicated. currently we simply extract the main URL and after running the tests do a dumb search/replace of that exact URL in the config file. If you can come up with a resilient approach how to change the URL of another repo to the main URL for all OSes and repo config types you are welcome to provide a PR.
