### ISSUE TITLE
Add the option to select country for ubuntu-based distro

### ISSUE THREAD

**Issue by cloudenum** [vegardit/fast-apt-mirror.sh#6]
As of now the [mirrors.txt](http://mirrors.ubuntu.com/mirrors.txt) will always return 
```
http://archive.ubuntu.com/ubuntu/
```

Which render this script become useless, because it is essentially just speed testing the default mirror (which again already being used in most cases).

By adding the country options this issue can be solved, another way is using automatic country detection using IP.

**Comment by cloudenum** [comment]
I've submitted a PR for this issue

**Comment by sebthom** [comment]
> As of now the [mirrors.txt](http://mirrors.ubuntu.com/mirrors.txt) will always return
> 
> ```
> http://archive.ubuntu.com/ubuntu/
> ```
> 

I wonder why this is. I am not aware of any announcement that http://mirrors.ubuntu.com/mirrors.txt is deprecated

**Comment by sebthom** [comment]
Fixed by https://github.com/vegardit/fast-apt-mirror.sh/commit/948aeb8fd163e3488612a53cd4ed68d7bb526eaa

I hope mirrors.txt will work again soon. I am not really happy about the need to manually specify the country.
